FROM node:lts as dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN yarn install


FROM node:lts as builder
WORKDIR /app
COPY ./ .
COPY --from=dependencies /app/node_modules ./node_modules
RUN yarn run build

RUN ls -l


FROM node:lts as runner
WORKDIR /app
ENV NODE_ENV production
COPY --from=builder /app/ .

ENV HOSTNAME="0.0.0.0"
EXPOSE 3000

CMD ["yarn", "start", "-p" , "3000"]